apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: reproduce-csl
spec:
  type: LoadBalancer
  selector:
    app: reproduce-csl
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
